name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: compile
        run: |
          deno compile --A --target x86_64-unknown-linux-gnu --output ./dist/node_prune_linux_x86_64 ./main.ts
          deno compile --A --target aarch64-unknown-linux-gnu --output ./dist/node_prune_linux_aarch64 ./main.ts
          deno compile --A --target x86_64-pc-windows-msvc --output ./dist/node_prune_windows_x86_64 ./main.ts
          deno compile --A --target x86_64-apple-darwin --output ./dist/node_prune_macos_x86_64 ./main.ts
          deno compile --A --target aarch64-apple-darwin --output ./dist/node_prune_macos_aarch64 ./main.ts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/node_prune_linux_x86_64
            dist/node_prune_linux_aarch64
            dist/node_prune_windows_x86_64.exe
            dist/node_prune_macos_x86_64
            dist/node_prune_macos_aarch64
